### ISSUE TITLE
Segfault/Core dump

### ISSUE THREAD

**Issue by pmos69** [vast-io/vast#111]
Seems cache related, but only seems to occur while an import is being made simultaneously.

The conditions to reproduce the segfault 100% of the times are:

1 - An import is being made
2 - Repeating a query/export.
The query should have a predicate of type `... && somefield=="value"`
(just something like &time<now won't trigger it)

The core.dumps might be a bit too big to post here.
Here's an example stack from a core dump:

```
[user@bro ~]$ gdb -se /usr/local/bin/vast
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) core vast.core
Core was generated by `vast'.
Program terminated with signal 11, Segmentation fault.
...
#0  vast::bitvector::block (this=0x80e77e6a8, b=0) at /home/user/myvast/vast/src/vast/bitvector.cc:410
410       return bits_[b];
[New Thread 803808c00 (LWP 100333/<unknown>)]
[New Thread 803808800 (LWP 100332/<unknown>)]
[New Thread 803808400 (LWP 100331/<unknown>)]
[New Thread 803808000 (LWP 100330/<unknown>)]
[New Thread 803807c00 (LWP 100329/<unknown>)]
[New Thread 803807800 (LWP 100328/<unknown>)]
[New Thread 803807400 (LWP 100327/<unknown>)]
[New Thread 803807000 (LWP 100324/<unknown>)]
[New Thread 803806c00 (LWP 100323/<unknown>)]
[New Thread 803806400 (LWP 100775/<unknown>)]
(gdb) info stack
#0  vast::bitvector::block (this=0x80e77e6a8, b=0) at /home/user/myvast/vast/src/vast/bitvector.cc:410
#1  0x0000000800ef75e8 in vast::ewah_bitstream::sequence_range::next_sequence (this=0x7fffdf5f8688, seq=@0x7fffdf5f8688)
    at /home/user/myvast/vast/src/vast/bitstream.cc:290
#2  0x0000000800ef8c6f in _ZN4vast5applyINS_14ewah_bitstreamEZNS_5nand_IS1_EET_RKS3_S5_EUlmmE_EES3_S5_S5_bbT0_ (lhs=@0x7fffdf5f8790,
    rhs=@0x80e77e6a8, fill_lhs=true, fill_rhs=false) at bitstream.h:297
#3  0x0000000800ef7ae6 in vast::ewah_bitstream::bitwise_subtract (this=0x7fffdf5f8790, other=@0x0) at bitstream.h:708
#4  0x0000000800f9eb9f in vast::operator- (x=<value optimized out>, y=<value optimized out>) at bitstream.h:481
#5  0x0000000800f865bc in caf::trivial_match_case<vast::index::make(caf::stateful_actor<vast::index::state, caf::event_based_actor>*, vast::path const&, unsigned long, unsigned long, unsigned long)::$_13>::invoke (this=0x80501c1a8, res=@0x7fffdf5f8d80,
    msg=<value optimized out>) at /home/user/myvast/vast/src/vast/actor/index.cc:526
#6  0x000000080183500f in caf::detail::behavior_impl::invoke (this=0x80501c080, msg=@0x80e64a448)
    at /home/user/actor-framework/libcaf_core/src/behavior_impl.cpp:82
#7  0x00000008018462ee in caf::local_actor::invoke_message (this=0x804cdf020, ptr=@0x7fffdf5f8f10, fun=<value optimized out>)
    at behavior.hpp:
```

Last log lines:

```
:: exporter#4130 received task from index
:: partition#24 got historical query: {&time < 2015-11-18+08:00:55 && time == "13:02:17"}
:: partition#24 spawns new query task
:: partition#24 dispatches predicate &time < 2015-11-18+08:00:55
:: partition#24 relays predicate for base 781
:: partition#24  - forwards predicate to #54
:: partition#24 relays predicate for base 815
:: partition#24  - forwards predicate to #53
:: partition#24 relays predicate for base 851
:: partition#24  - forwards predicate to #51
:: partition#24 relays predicate for base 888
:: partition#24  - forwards predicate to #50
:: partition#24 relays predicate for base 897
:: partition#24  - forwards predicate to #48
:: partition#24 relays predicate for base 906
:: partition#24  - forwards predicate to #47
:: partition#24 relays predicate for base 912
:: partition#24  - forwards predicate to #46
:: partition#24 relays predicate for base 947
:: partition#24  - forwards predicate to #45
:: partition#24 relays predicate for base 1721
:: partition#24  - forwards predicate to #159
:: partition#24 relays predicate for base 1762
:: partition#24  - forwards predicate to #488
:: partition#24 relays predicate for base 1779
:: partition#24  - forwards predicate to #854
:: partition#24 relays predicate for base 1792
:: partition#24  - forwards predicate to #1284
:: partition#24 relays predicate for base 1870
:: partition#24  - forwards predicate to #1650
:: partition#24 relays predicate for base 1888
:: partition#24  - forwards predicate to #1993
:: partition#24 relays predicate for base 1950
:: partition#24  - forwards predicate to #2359
:: partition#24 relays predicate for base 2023
:: partition#24  - forwards predicate to #2712
:: partition#24 relays predicate for base 2099
:: partition#24  - forwards predicate to #3092
:: partition#24 relays predicate for base 2131
:: partition#24  - forwards predicate to #3435
:: partition#24 relays predicate for base 2148
:: partition#24  - forwards predicate to #3801
:: partition#24 dispatches predicate time == "13:02:17"
:: partition#24 skips indexers for base 781
:: partition#24 skips indexers for base 815
:: partition#24 skips indexers for base 851
:: partition#24 skips indexers for base 888
:: partition#24 skips indexers for base 897
:: partition#24 skips indexers for base 906
:: partition#24 skips indexers for base 912
:: partition#24 skips indexers for base 947
:: partition#24 skips indexers for base 1721
:: partition#24 skips indexers for base 1762
:: partition#24 skips indexers for base 1779
:: partition#24 relays predicate for base 1792
:: partition#24  - forwards predicate to #1284
:: partition#24 relays predicate for base 1870
:: partition#24  - forwards predicate to #1650
:: partition#24 relays predicate for base 1888
:: partition#24  - forwards predicate to #1993
:: partition#24 relays predicate for base 1950
:: partition#24  - forwards predicate to #2359
:: partition#24 relays predicate for base 2023
:: partition#24  - forwards predicate to #2712
:: partition#24 relays predicate for base 2099
:: partition#24  - forwards predicate to #3092
:: partition#24 relays predicate for base 2131
:: partition#24  - forwards predicate to #3435
:: partition#24 relays predicate for base 2148
:: partition#24  - forwards predicate to #3801
:: task#4134 spawned
:: event-data-indexer#3843 looks up predicate: time == "13:02:17"
:: partition#24 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#3802 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 2 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#3502 looks up predicate: time == "13:02:17"
:: partition#24 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#3436 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 5 hits for predicate: &time < 2015-11-18+08:00:55
:: task#4131 spawned
:: partition#23 got historical query: {&time < 2015-11-18+08:00:55 && time == "13:02:17"}
:: partition#23 spawns new query task
:: partition#23 dispatches predicate &time < 2015-11-18+08:00:55
:: event-data-indexer#3134 looks up predicate: time == "13:02:17"
:: partition#23 relays predicate for base 768
:: partition#23  - forwards predicate to #35
:: partition#24 got 0 hits for predicate: time == "13:02:17"
:: partition#23 relays predicate for base 787
:: partition#23  - forwards predicate to #33
:: event-time-indexer#3093 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 relays predicate for base 816
:: partition#23  - forwards predicate to #43
:: partition#23 relays predicate for base 856
:: partition#24 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#23  - forwards predicate to #44
:: partition#23 relays predicate for base 889
:: partition#23  - forwards predicate to #42
:: partition#23 relays predicate for base 898
:: partition#23  - forwards predicate to #40
:: partition#23 relays predicate for base 907
:: partition#23  - forwards predicate to #39
:: partition#23 relays predicate for base 913
:: partition#23  - forwards predicate to #38
:: partition#23 relays predicate for base 948
:: partition#23  - forwards predicate to #36
:: partition#23 relays predicate for base 1664
:: partition#23  - forwards predicate to #71
:: partition#23 relays predicate for base 1758
:: partition#23  - forwards predicate to #437
:: partition#23 relays predicate for base 1775
:: partition#23  - forwards predicate to #766
:: partition#23 relays predicate for base 1791
:: partition#23  - forwards predicate to #1132
:: partition#23 relays predicate for base 1840
:: partition#23  - forwards predicate to #1562
:: partition#23 relays predicate for base 1887
:: partition#23  - forwards predicate to #1942
:: partition#23 relays predicate for base 1916
:: partition#23  - forwards predicate to #2271
:: event-data-indexer#2779 looks up predicate: time == "13:02:17"
:: partition#23 relays predicate for base 2021
:: partition#23  - forwards predicate to #2661
:: partition#24 got 0 hits for predicate: time == "13:02:17"
:: partition#23 relays predicate for base 2056
:: partition#23  - forwards predicate to #3004
:: event-time-indexer#2713 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 relays predicate for base 2129
:: partition#23  - forwards predicate to #3384
:: partition#23 relays predicate for base 2141
:: partition#23  - forwards predicate to #3713
:: partition#23 relays predicate for base 2158
:: partition#24 got 19 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#23  - forwards predicate to #4079
:: partition#23 dispatches predicate time == "13:02:17"
:: partition#23 skips indexers for base 768
:: partition#23 skips indexers for base 787
:: partition#23 skips indexers for base 816
:: partition#23 skips indexers for base 856
:: partition#23 skips indexers for base 889
:: partition#23 skips indexers for base 898
:: partition#23 skips indexers for base 907
:: partition#23 skips indexers for base 913
:: partition#23 skips indexers for base 948
:: partition#23 skips indexers for base 1664
:: partition#23 skips indexers for base 1758
:: partition#23 skips indexers for base 1775
:: partition#23 skips indexers for base 1791
:: partition#23 relays predicate for base 1840
:: event-data-indexer#2401 looks up predicate: time == "13:02:17"
:: partition#23  - forwards predicate to #1562
:: partition#23 relays predicate for base 1887
:: partition#23  - forwards predicate to #1942
:: partition#23 relays predicate for base 1916
:: partition#23  - forwards predicate to #2271
:: partition#24 got 0 hits for predicate: time == "13:02:17"
:: partition#23 relays predicate for base 2021
:: partition#23  - forwards predicate to #2661
:: event-time-indexer#2360 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 relays predicate for base 2056
:: partition#23  - forwards predicate to #3004
:: partition#23 relays predicate for base 2129
:: partition#24 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#23  - forwards predicate to #3384
:: partition#23 relays predicate for base 2141
:: partition#23  - forwards predicate to #3713
:: partition#23 relays predicate for base 2158
:: partition#23  - forwards predicate to #4079
:: task#4137 spawned
:: event-data-indexer#2060 looks up predicate: time == "13:02:17"
:: partition#24 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#1994 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 19 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#4121 looks up predicate: time == "13:02:17"
:: partition#23 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#4080 looks up predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#1692 looks up predicate: time == "13:02:17"
:: partition#23 got 2 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#1651 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#1351 looks up predicate: time == "13:02:17"
:: partition#24 got 0 hits for predicate: time == "13:02:17"
:: task#4134 terminated (done)
:: partition#24 took 3.44ms to complete predicate for 19 indexers: time == "13:02:17"
:: partition#24 evaluates {&time < 2015-11-18+08:00:20 && time == "13:02:17"}
:: partition#24 evaluates {&time < 2015-11-18+08:00:55 && time == "13:02:17"}
:: event-time-indexer#1285 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 31 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#3780 looks up predicate: time == "13:02:17"
:: event-time-indexer#855 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#3714 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 2 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#489 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 7 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 7 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#160 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#1188 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#1191 looks up predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#3426 looks up predicate: time == "13:02:17"
:: partition#24 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#1194 looks up predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#3385 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 2 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#1197 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#1199 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#1201 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 5 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#1203 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#24 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#3071 looks up predicate: time == "13:02:17"
:: event-time-indexer#1205 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 0 hits for predicate: time == "13:02:17"
:: partition#24 got 6 hits for predicate: &time < 2015-11-18+08:00:55
:: task#4133 spawned
:: event-time-indexer#3005 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 43 hits for predicate: &time < 2015-11-18+08:00:55
:: task#4133 terminated (done)
:: partition#24 took 4.97ms to complete predicate for 19 indexers: &time < 2015-11-18+08:00:55
:: partition#24 evaluates {&time < 2015-11-18+08:00:55 && time == "13:02:17"}
:: task#4132 spawned
:: task#4132 terminated (done)
:: partition#24 completed query {&time < 2015-11-18+08:00:55 && time == "13:02:17"} in 5.17ms
:: index#14 got signal that #24 took 5.18ms to complete query:  {&time < 2015-11-18+08:00:55 && time == "13:02:17"}
:: event-data-indexer#2703 looks up predicate: time == "13:02:17"
:: index#14 consolidates 8f1affb1-06db-47a6-ac79-9447c078acaf for {&time < 2015-11-18+08:00:55 && time == "13:02:17"}
:: index#14 removes partition from schedule: 8f1affb1-06db-47a6-ac79-9447c078acaf
:: partition#23 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#2662 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 2 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#25 got historical query: {&time < 2015-11-18+08:00:55 && time == "13:02:17"}
:: partition#25 spawns new query task
:: partition#25 dispatches predicate &time < 2015-11-18+08:00:55
:: partition#25 relays predicate for base 780
:: partition#25  - forwards predicate to #62
:: partition#25 relays predicate for base 796
:: partition#25  - forwards predicate to #63
:: partition#25 relays predicate for base 849
:: partition#25  - forwards predicate to #64
:: partition#25 relays predicate for base 869
:: partition#25  - forwards predicate to #66
:: partition#25 relays predicate for base 896
:: partition#25  - forwards predicate to #67
:: partition#25 relays predicate for base 904
:: partition#25  - forwards predicate to #68
:: partition#25 relays predicate for base 911
:: partition#25  - forwards predicate to #65
:: partition#25 relays predicate for base 945
:: partition#25  - forwards predicate to #61
:: partition#25 relays predicate for base 1722
:: partition#25  - forwards predicate to #210
:: partition#25 relays predicate for base 1769
:: partition#25  - forwards predicate to #576
:: partition#25 relays predicate for base 1781
:: partition#25  - forwards predicate to #905
:: partition#25 relays predicate for base 1823
:: event-data-indexer#2338 looks up predicate: time == "13:02:17"
:: partition#25  - forwards predicate to #1372
:: partition#25 relays predicate for base 1871
:: partition#25  - forwards predicate to #1715
:: partition#25 relays predicate for base 1907
:: partition#25  - forwards predicate to #2081
:: partition#23 got 0 hits for predicate: time == "13:02:17"
:: partition#25 relays predicate for base 1951
:: partition#25  - forwards predicate to #2410
:: partition#25 relays predicate for base 2042
:: event-time-indexer#2272 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#25  - forwards predicate to #2800
:: partition#25 relays predicate for base 2100
:: partition#25  - forwards predicate to #3157
:: partition#25 relays predicate for base 2136
:: partition#25  - forwards predicate to #3523
:: partition#25 relays predicate for base 2150
:: partition#25  - forwards predicate to #3852
:: partition#23 got 34 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#25 dispatches predicate time == "13:02:17"
:: partition#25 skips indexers for base 780
:: partition#25 skips indexers for base 796
:: partition#25 skips indexers for base 849
:: partition#25 skips indexers for base 869
:: partition#25 skips indexers for base 896
:: partition#25 skips indexers for base 904
:: partition#25 skips indexers for base 911
:: partition#25 skips indexers for base 945
:: partition#25 skips indexers for base 1722
:: partition#25 skips indexers for base 1769
:: partition#25 skips indexers for base 1781
:: partition#25 relays predicate for base 1823
:: partition#25  - forwards predicate to #1372
:: partition#25 relays predicate for base 1871
:: partition#25  - forwards predicate to #1715
:: partition#25 relays predicate for base 1907
:: partition#25  - forwards predicate to #2081
:: partition#25 relays predicate for base 1951
:: partition#25  - forwards predicate to #2410
:: partition#25 relays predicate for base 2042
:: partition#25  - forwards predicate to #2800
:: partition#25 relays predicate for base 2100
:: event-data-indexer#1984 looks up predicate: time == "13:02:17"
:: partition#25  - forwards predicate to #3157
:: partition#25 relays predicate for base 2136
:: partition#25  - forwards predicate to #3523
:: partition#25 relays predicate for base 2150
:: partition#25  - forwards predicate to #3852
:: partition#23 got 0 hits for predicate: time == "13:02:17"
:: index#14 received 2 historical hits from #25 for query: {&time < 2015-11-18+08:00:55 && time == "13:02:17"}
:: event-time-indexer#1943 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: exporter#4130 prefetches chunk for ID 946
:: exporter#4130 becomes waiting (pending in-flight chunks)
:: archive#13 got request for event 946
:: archive#13 delivers chunk [945,947)
:: exporter#4130 got chunk [945,947)
:: exporter#4130 becomes extracting
:: exporter#4130 looks for next unprocessed ID after 946
:: exporter#4130 extracts 1
:: exporter#4130 got request to drain and terminate
:: event-data-indexer#1629 looks up predicate: time == "13:02:17"
:: partition#23 got 0 hits for predicate: time == "13:02:17"
:: task#4137 terminated (done)
:: partition#23 took 3.96ms to complete predicate for 21 indexers: time == "13:02:17"
:: partition#23 evaluates {&time < 2015-11-18+08:00:20 && time == "13:02:17"}
:: partition#23 evaluates {&time < 2015-11-18+08:00:55 && time == "13:02:17"}
:: event-time-indexer#1563 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 30 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#1133 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#767 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 4 hits for predicate: &time < 2015-11-18+08:00:55
:: exporter#4130 resolved AST for bro::FortiOS::traffic::forward: {&time < 2015-11-18+08:00:55 && bro::FortiOS::traffic::forward@64 == "13:02:17"}
:: event-time-indexer#438 looks up predicate: &time < 2015-11-18+08:00:55
:: exporter#4130 extracted 2 events (2/0 processed/remaining hits in current chunk)
:: partition#23 got 4 hits for predicate: &time < 2015-11-18+08:00:55
:: exporter#4130 becomes idle (no more in-flight chunks)
:: event-time-indexer#72 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 57 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#1216 looks up predicate: &time < 2015-11-18+08:00:55
:: task#4140 spawned
:: event-data-indexer#3919 looks up predicate: time == "13:02:17"
:: partition#25 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#3853 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#25 got 4 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#3565 looks up predicate: time == "13:02:17"
:: partition#25 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#3524 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#25 got 2 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#3224 looks up predicate: time == "13:02:17"
:: partition#25 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#3158 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#25 got 21 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#2842 looks up predicate: time == "13:02:17"
:: partition#25 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#2801 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#25 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#2477 looks up predicate: time == "13:02:17"
:: partition#25 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#2411 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#25 got 4 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#2123 looks up predicate: time == "13:02:17"
:: partition#25 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#2082 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#25 got 5 hits for predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#1782 looks up predicate: time == "13:02:17"
:: partition#25 got 0 hits for predicate: time == "13:02:17"
:: event-time-indexer#1716 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#25 got 5 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#23 got 1 hits for predicate: &time < 2015-11-18+08:00:55
:: event-time-indexer#1238 looks up predicate: &time < 2015-11-18+08:00:55
:: event-data-indexer#1414 looks up predicate: time == "13:02:17"
:: partition#25 got 0 hits for predicate: time == "13:02:17"
:: task#4140 terminated (done)
:: partition#23 got 2 hits for predicate: &time < 2015-11-18+08:00:55
:: partition#25 took 4.50ms to complete predicate for 19 indexers: time == "13:02:17"
:: partition#25 evaluates {&time < 2015-11-18+08:00:20 && time == "13:02:17"}
:: event-time-indexer#1244 looks up predicate: &time < 2015-11-18+08:00:55
:: partition#25 relays 2 hits
:: partition#25 evaluates {&time < 2015-11-18+08:00:55 && time == "13:02:17"}
Segmentation fault (core dumped)
```

**Comment by mavam** [comment]
I'm closing this for now since VAST underwent a substantial rewrite. Please re-open of the issue still persists.
