### ISSUE TITLE
Import over the network (somtimes) leads to segmentation fault

### ISSUE THREAD

**Issue by josephnoir** [vast-io/vast#120]
Setup:
* VAST node on a Linux host (Ubuntu 17.04, compiled with GCC 6.3) started with `build/bin/vast start -f`
* Second node that imports data to it (macOS 0.12.4, compiled with Apple LLVM version 8.1.0) using `cat ./libvast/test/logs/bro/ssl.log | ./build/bin/vast -e localhost:42000 import bro`
* Connection via ssh tunnel `ssh -NL 42000:localhost:42000 user@host` (don't think this matters, but who knows)

CAF and VASt were compiled with log level debug on both sides to get some feedback on what is happening.

<details>
<summary>logs</summary>

server side + backtrace

```
$ gdb --args ./build/bin/vast start -f
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/bin/vast...done.
(gdb) r
Starting program: $HOME/Git/vast/build/bin/vast start -f
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3da1700 (LWP 2769)]
[New Thread 0x7ffff2da0700 (LWP 2770)]
[New Thread 0x7ffff209f700 (LWP 2771)]
[New Thread 0x7ffff189e700 (LWP 2772)]
[New Thread 0x7ffff109d700 (LWP 2773)]
[New Thread 0x7ffff089c700 (LWP 2774)]
[New Thread 0x7fffebfff700 (LWP 2775)]
[New Thread 0x7fffeb7fe700 (LWP 2776)]
[New Thread 0x7fffeaffd700 (LWP 2777)]
[New Thread 0x7fffea7fc700 (LWP 2778)]
[New Thread 0x7fffe9ffb700 (LWP 2779)]
[New Thread 0x7fffe97fa700 (LWP 2780)]
[New Thread 0x7fffe8ff9700 (LWP 2781)]
[New Thread 0x7fffdffff700 (LWP 2782)]
[New Thread 0x7fffdf7fe700 (LWP 2783)]
[New Thread 0x7fffdeffd700 (LWP 2784)]
[New Thread 0x7fffde7fc700 (LWP 2785)]
     _   _____   __________
    | | / / _ | / __/_  __/
    | |/ / __ |_\ \  / /
    |___/_/ |_/___/ /_/  0.1

spawning local node: mobi35
mobi35 got command spawn ("metastore")
tracker got new metastore (metastore)
mobi35 got command spawn ("archive")
tracker got new archive (archive)
mobi35 got command spawn ("index")
tracker got new index (index)
index caps partitions at 1048576 events
index keeps at most 10 partitions in memory
mobi35 got command spawn ("importer")
mobi35 auto-generated new label: importer-1
tracker got new importer (importer-1)
server#4490910421643582870 loaded persistent state: id = 4490910421643582870, current term 5, voted for 4490910421643582870
follower#4490910421643582870 starts in term 5
follower#4490910421643582870 previously voted for server 4490910421643582870
listening on :42000
signal-monitor sends signals to 8
signal-monitor registers signal handler for Hangup
signal-monitor registers signal handler for Interrupt
signal-monitor registers signal handler for Quit
signal-monitor registers signal handler for Terminated
signal-monitor registers signal handler for User defined signal 1
signal-monitor registers signal handler for User defined signal 2
accountant opens log file: vast/log/current/accounting.log
importer found 30 local IDs
archive registers accountant 10
importer found next ID: 226
importer registers meta store
importer registers archive 14
importer registers index 15
follower#4490910421643582870 initialized log in range [1,11]
follower#4490910421643582870 becomes leader in term 6
leader#4490910421643582870 advances commitIndex 0 -> 12
leader#4490910421643582870 got subscribe request from 13
leader#4490910421643582870 sends entries 1 to 12
leader#4490910421643582870 skips delivery of no-op entry 1
leader#4490910421643582870 skips delivery of no-op entry 2
leader#4490910421643582870 skips delivery of no-op entry 3
leader#4490910421643582870 skips delivery of no-op entry 4
leader#4490910421643582870 delivers entry 5 (59D94A8F88275F5CE3F565CCEECB7C3539BCFF00#17137, 13, 1, ('add', "id", 256))
leader#4490910421643582870 skips delivery of no-op entry 6
leader#4490910421643582870 skips delivery of no-op entry 7
leader#4490910421643582870 skips delivery of no-op entry 8
leader#4490910421643582870 skips delivery of no-op entry 9
leader#4490910421643582870 skips delivery of no-op entry 10
leader#4490910421643582870 skips delivery of no-op entry 11
leader#4490910421643582870 skips delivery of no-op entry 12
replicated-store applies entry 5 (consensus update)
replicated-store got remote operation 1
replicated-store applies ADD
replicated-store gathers statistics
*** unhandled exception: [id: 16, name: importer, exception typeid: St12length_error]: vector::_M_default_append
importer got 113 events
importer ships 113 events
archive got 113 events [226,339)
index got 113 events [226,339)
index spawns new active partition 16426281-5301-4aa1-9325-0870a418cb7b
partition got 113 events
event-indexer operates for event bro::ssl
event-indexer didn't find persistent state, spawning new indexers
event-indexer spawns field indexer at offset 0 with type time
event-indexer spawns field indexer at offset 1 with type string
event-indexer spawns field indexer at offset 2,0 with type addr
event-indexer spawns field indexer at offset 2,1 with type port
event-indexer spawns field indexer at offset 2,2 with type addr
event-indexer spawns field indexer at offset 2,3 with type port
event-indexer spawns field indexer at offset 3 with type string
event-indexer spawns field indexer at offset 4 with type string
event-indexer spawns field indexer at offset 5 with type string
event-indexer spawns field indexer at offset 6 with type string
event-indexer spawns field indexer at offset 7 with type string
event-indexer spawns field indexer at offset 8 with type string
event-indexer spawns field indexer at offset 9 with type time
event-indexer spawns field indexer at offset 10 with type time
event-indexer spawns field indexer at offset 11 with type string
event-indexer spawns field indexer at offset 12 with type string
event-indexer spawns field indexer at offset 13 with type string

Thread 9 "vast" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb7fe700 (LWP 2776)]
vast::inspect<vast::detail::hash_inspector<vast::xxhash32> > (i=..., f=<synthetic pointer>...) at $HOME/Git/vast/libvast/vast/type.hpp:559
559	    return f(i.types);
(gdb) bt
#0  vast::inspect<vast::detail::hash_inspector<vast::xxhash32> > (i=..., f=<synthetic pointer>...) at $HOME/Git/vast/libvast/vast/type.hpp:559
#1  vast::hash_append<vast::xxhash32, vast::type::impl> (x=..., h=...) at $HOME/Git/vast/libvast/vast/concept/hashable/hash_append.hpp:425
#2  vast::detail::hash_inspector<vast::xxhash32>::operator()<vast::type::impl&> (x=..., this=<synthetic pointer>) at $HOME/Git/vast/libvast/vast/concept/hashable/hash_append.hpp:410
#3  vast::inspect<vast::detail::hash_inspector<vast::xxhash32> > (t=..., f=<synthetic pointer>...) at $HOME/Git/vast/libvast/vast/type.hpp:125
#4  vast::hash_append<vast::xxhash32, vast::type> (x=..., h=...) at $HOME/Git/vast/libvast/vast/concept/hashable/hash_append.hpp:425
#5  vast::uhash<vast::xxhash32>::operator()<vast::type> (x=..., this=0x7fffeb7fd6d0) at $HOME/Git/vast/libvast/vast/concept/hashable/uhash.hpp:20
#6  std::hash<vast::type>::operator() (this=0x7fffeb7fd8c8, t=...) at $HOME/Git/vast/libvast/vast/type.hpp:578
#7  std::__detail::_Hash_code_base<vast::type, std::pair<vast::type const, unsigned int>, std::__detail::_Select1st, std::hash<vast::type>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, true>::_M_hash_code (this=0x7fffeb7fd8c8, __k=...) at /usr/include/c++/6/bits/hashtable_policy.h:1255
#8  std::_Hashtable<vast::type, std::pair<vast::type const, unsigned int>, std::allocator<std::pair<vast::type const, unsigned int> >, std::__detail::_Select1st, std::equal_to<vast::type>, std::hash<vast::type>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find (__k=..., this=0x7fffeb7fd8c8) at /usr/include/c++/6/bits/hashtable.h:1292
#9  std::unordered_map<vast::type, unsigned int, std::hash<vast::type>, std::equal_to<vast::type>, std::allocator<std::pair<vast::type const, unsigned int> > >::find (__x=..., this=0x7fffeb7fd8c8) at /usr/include/c++/6/bits/unordered_map.h:851
#10 vast::batch::writer::write (this=this@entry=0x7fffeb7fd860, e=...) at $HOME/Git/vast/libvast/src/batch.cpp:54
#11 0x00007ffff78be3b8 in vast::system::<lambda(const std::vector<vast::event, std::allocator<vast::event> >&)>::operator()(const std::vector<vast::event, std::allocator<vast::event> > &) const (__closure=__closure@entry=0x7fffbc000e60, events=std::vector of length 113, capacity 128 = {...}) at $HOME/Git/vast/libvast/src/system/archive.cpp:169
#12 0x00007ffff78bef25 in caf::lfinvoker<true, vast::system::archive(caf::typed_actor<caf::typed_mpi<caf::detail::type_list<std::vector<vast::event, std::allocator<vast::event> > >, caf::output_tuple<void> >, caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)16840633901u> >, caf::output_tuple<caf::atom_constant<(caf::atom_value)64816u> > >, caf::typed_mpi<caf::detail::type_list<vast::bitmap>, caf::output_tuple<std::vector<vast::event, std::allocator<vast::event> > > > >::stateful_pointer<vast::system::archive_state>, vast::path, size_t, size_t)::<lambda(const std::vector<vast::event, std::allocator<vast::event> >&)> >::operator()<std::vector<vast::event, std::allocator<vast::event> >&> (
    this=<synthetic pointer>) at $HOME/Git/actor-framework/libcaf_core/caf/match_case.hpp:94
#13 caf::detail::apply_args<caf::lfinvoker<true, vast::system::archive(caf::typed_actor<caf::typed_mpi<caf::detail::type_list<std::vector<vast::event, std::allocator<vast::event> > >, caf::output_tuple<void> >, caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)16840633901u> >, caf::output_tuple<caf::atom_constant<(caf::atom_value)64816u> > >, caf::typed_mpi<caf::detail::type_list<vast::bitmap>, caf::output_tuple<std::vector<vast::event, std::allocator<vast::event> > > > >::stateful_pointer<vast::system::archive_state>, vast::path, size_t, size_t)::<lambda(const std::vector<vast::event>&)> >, 0l, caf::detail::pseudo_tuple<std::vector<vast::event, std::allocator<vast::event> > > > (
    tup=<synthetic pointer>..., f=<synthetic pointer>...) at $HOME/Git/actor-framework/libcaf_core/caf/detail/apply_args.hpp:40
#14 caf::trivial_match_case<vast::system::archive(caf::typed_actor<caf::typed_mpi<caf::detail::type_list<std::vector<vast::event, std::allocator<vast::event> > >, caf::output_tuple<void> >, caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)16840633901u> >, caf::output_tuple<caf::atom_constant<(caf::atom_value)64816u> > >, caf::typed_mpi<caf::detail::type_list<vast::bitmap>, caf::output_tuple<std::vector<vast::event, std::allocator<vast::event> > > > >::stateful_pointer<vast::system::archive_state>, vast::path, size_t, size_t)::<lambda(const std::vector<vast::event, std::allocator<vast::event> >&)> >::invoke(caf::detail::invoke_result_visitor &, caf::type_erased_tuple &) (this=0x7fffbc000e50,
    f=..., xs=...) at $HOME/Git/actor-framework/libcaf_core/caf/match_case.hpp:164
#15 0x00007ffff716b74f in caf::detail::behavior_impl::invoke (this=0x7fffbc000df0, f=..., xs=...) at $HOME/Git/actor-framework/libcaf_core/src/behavior_impl.cpp:107
#16 0x00007ffff71bbf45 in caf::behavior::operator() (xs=..., f=..., this=0x7fffbc000c50) at $HOME/Git/actor-framework/libcaf_core/caf/behavior.hpp:111
#17 caf::scheduled_actor::consume (this=0x7fffbc001100, x=...) at $HOME/Git/actor-framework/libcaf_core/src/scheduled_actor.cpp:484
#18 0x00007ffff71b81c4 in caf::scheduled_actor::reactivate (this=this@entry=0x7fffbc001100, x=...) at $HOME/Git/actor-framework/libcaf_core/src/scheduled_actor.cpp:583
#19 0x00007ffff71b9704 in caf::scheduled_actor::resume (this=0x7fffbc001100, ctx=<optimized out>, max_throughput=18446744073709551615) at $HOME/Git/actor-framework/libcaf_core/src/scheduled_actor.cpp:231
#20 0x00007ffff715e103 in caf::scheduler::worker<caf::policy::work_stealing>::run (this=<optimized out>) at $HOME/Git/actor-framework/libcaf_core/caf/scheduler/worker.hpp:116
#21 caf::scheduler::worker<caf::policy::work_stealing>::start()::{lambda()#1}::operator()() const (__closure=<optimized out>) at $HOME/Git/actor-framework/libcaf_core/caf/scheduler/worker.hpp:58
#22 std::_Bind_simple<caf::scheduler::worker<caf::policy::work_stealing>::start()::{lambda()#1} ()>::_M_invoke<>(std::_Index_tuple<>) (this=<optimized out>) at /usr/include/c++/6/functional:1391
#23 std::_Bind_simple<caf::scheduler::worker<caf::policy::work_stealing>::start()::{lambda()#1} ()>::operator()() (this=<optimized out>) at /usr/include/c++/6/functional:1380
#24 std::thread::_State_impl<std::_Bind_simple<caf::scheduler::worker<caf::policy::work_stealing>::start()::{lambda()#1} ()> >::_M_run() (this=<optimized out>) at /usr/include/c++/6/thread:197
#25 0x00007ffff65d0e6f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#26 0x00007ffff5a48424 in start_thread (arg=0x7fffeb7fe700) at pthread_create.c:333
#27 0x00007ffff5d469bf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
(gdb)
```

Importer on the client side.

```
$ cat ./libvast/test/logs/bro/ssl.log | ./build/bin/vast -e localhost:42000 import bro
     _   _____   __________
    | | / / _ | / __/_  __/
    | |/ / __ |_\ \  / /
    |___/_/ |_/___/ /_/  0.1

connecting to localhost:42000
signal-monitor sends signals to 8
signal-monitor registers signal handler for Hangup: 1
signal-monitor registers signal handler for Interrupt: 2
signal-monitor registers signal handler for Quit: 3
signal-monitor registers signal handler for Terminated: 15
signal-monitor registers signal handler for User defined signal 1: 30
signal-monitor registers signal handler for User defined signal 2: 31
connecting source to importers
bro-reader registers sink 16
bro-reader parsed bro header:
bro-reader     #separator
bro-reader     #set_separator ,
bro-reader     #empty_field (empty)
bro-reader     #unset_field -
bro-reader     #path ssl
bro-reader     #fields:
bro-reader       0) ts: time
bro-reader       1) uid: string
bro-reader       2) id.orig_h: addr
bro-reader       3) id.orig_p: port
bro-reader       4) id.resp_h: addr
bro-reader       5) id.resp_p: port
bro-reader       6) version: string
bro-reader       7) cipher: string
bro-reader       8) server_name: string
bro-reader       9) session_id: string
bro-reader       10) subject: string
bro-reader       11) issuer_subject: string
bro-reader       12) not_valid_before: time
bro-reader       13) not_valid_after: time
bro-reader       14) last_alert: string
bro-reader       15) client_subject: string
bro-reader       16) client_issuer_subject: string
bro-reader auto-detected field 0 as event timestamp
bro-reader ignored comment at line 122: #close	2014-05-23-18-02-35
got end_of_input: ("input exhausted")
bro-reader produced 113 events in +1660173ns (68072 events/sec)
received DOWN from source
```

</details>

**Comment by josephnoir** [comment]
This can also happens on a local import. (The data format we used was Bro.)

<details>
<summary>Backtrace</summary>

```
     _   _____   __________
    | | / / _ | / __/_  __/
    | |/ / __ |_\ \  / /
    |___/_/ |_/___/ /_/  0.1

spawning local node: $HOSTNAME
listening on :42000
[New Thread 0x7fffd6ffd700 (LWP 173975)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffec7d9700 (LWP 173941)]
inspect<vast::detail::hash_inspector<vast::xxhash32> > (i=..., f=<synthetic pointer>) at $HOME/persistent_vast/vast/libvast/vast/type.hpp:559
559         return f(i.types);
Missing separate debuginfos, use: debuginfo-install gperftools-libs-2.4-8.el7.x86_64 libpcap-1.5.3-8.el7.x86_64 libunwind-1.1-5.el7_2.2.x86_64
(gdb) bt
#0  inspect<vast::detail::hash_inspector<vast::xxhash32> > (i=..., f=<synthetic pointer>) at $HOME/persistent_vast/vast/libvast/vast/type.hpp:559
#1  hash_append<vast::xxhash32, vast::type::impl> (x=..., h=...) at $HOME/persistent_vast/vast/libvast/vast/concept/hashable/hash_append.hpp:425
#2  operator()<vast::type::impl&> (x=..., this=<synthetic pointer>) at $HOME/persistent_vast/vast/libvast/vast/concept/hashable/hash_append.hpp:410
#3  inspect<vast::detail::hash_inspector<vast::xxhash32> > (t=..., f=<synthetic pointer>) at $HOME/persistent_vast/vast/libvast/vast/type.hpp:125
#4  hash_append<vast::xxhash32, vast::type> (x=..., h=...) at $HOME/persistent_vast/vast/libvast/vast/concept/hashable/hash_append.hpp:425
#5  operator()<vast::type> (x=..., this=0x7fffec7d8760) at $HOME/persistent_vast/vast/libvast/vast/concept/hashable/uhash.hpp:20
#6  operator() (this=0x7fffec7d8958, t=...) at $HOME/persistent_vast/vast/libvast/vast/type.hpp:578
#7  _M_hash_code (this=0x7fffec7d8958, __k=...) at /usr/local/include/c++/6.3.0/bits/hashtable_policy.h:1255
#8  find (__k=..., this=0x7fffec7d8958) at /usr/local/include/c++/6.3.0/bits/hashtable.h:1292
#9  find (__x=..., this=0x7fffec7d8958) at /usr/local/include/c++/6.3.0/bits/unordered_map.h:851
#10 vast::batch::writer::write (this=this@entry=0x7fffec7d88f0, e=...) at $HOME/persistent_vast/vast/libvast/src/batch.cpp:54
#11 0x00007ffff789e8d8 in vast::system::<lambda(const std::vector<vast::event, std::allocator<vast::event> >&)>::operator()(const std::vector<vast::event, std::allocator<vast::event> > &) const (__closure=__closure@entry=0x7fffbc0015b0, events=...) at $HOME/persistent_vast/vast/libvast/src/system/archive.cpp:169
#12 0x00007ffff789f425 in operator()<std::vector<vast::event, std::allocator<vast::event> >&> (this=<synthetic pointer>) at $HOME/persistent_vast/actor-framework/libcaf_core/caf/match_case.hpp:94
#13 apply_args<caf::lfinvoker<true, vast::system::archive(caf::typed_actor<caf::typed_mpi<caf::detail::type_list<std::vector<vast::event, std::allocator<vast::event> > >, caf::output_tuple<void> >, caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)16840633901u> >, caf::output_tuple<caf::atom_constant<(caf::atom_value)64816u> > >, caf::typed_mpi<caf::detail::type_list<vast::bitmap>, caf::output_tuple<std::vector<vast::event, std::allocator<vast::event> > > > >::stateful_pointer<vast::system::archive_state>, vast::path, size_t, size_t)::<lambda(const std::vector<vast::event>&)> >, 0l, caf::detail::pseudo_tuple<std::vector<vast::event, std::allocator<vast::event> > > > (tup=<synthetic pointer>,
    f=<synthetic pointer>) at $HOME/persistent_vast/actor-framework/libcaf_core/caf/detail/apply_args.hpp:40
#14 caf::trivial_match_case<vast::system::archive(caf::typed_actor<caf::typed_mpi<caf::detail::type_list<std::vector<vast::event, std::allocator<vast::event> > >, caf::output_tuple<void> >, caf::typed_mpi<caf::detail::type_list<caf::atom_constant<(caf::atom_value)16840633901u> >, caf::output_tuple<caf::atom_constant<(caf::atom_value)64816u> > >, caf::typed_mpi<caf::detail::type_list<vast::bitmap>, caf::output_tuple<std::vector<vast::event, std::allocator<vast::event> > > > >::stateful_pointer<vast::system::archive_state>, vast::path, size_t, size_t)::<lambda(const std::vector<vast::event, std::allocator<vast::event> >&)> >::invoke(caf::detail::invoke_result_visitor &, caf::type_erased_tuple &) (this=0x7fffbc0015a0,
    f=..., xs=...) at $HOME/persistent_vast/actor-framework/libcaf_core/caf/match_case.hpp:164
#15 0x00007ffff714c46f in caf::detail::behavior_impl::invoke (this=0x7fffbc001540, f=..., xs=...) at $HOME/persistent_vast/actor-framework/libcaf_core/src/behavior_impl.cpp:107
#16 0x00007ffff719a785 in operator() (xs=..., f=..., this=0x7fffbc000980) at $HOME/persistent_vast/actor-framework/libcaf_core/caf/behavior.hpp:111
#17 caf::scheduled_actor::consume (this=<optimized out>, x=...) at $HOME/persistent_vast/actor-framework/libcaf_core/src/scheduled_actor.cpp:500
#18 0x00007ffff71979eb in caf::scheduled_actor::reactivate (this=this@entry=0x7fffbc0017f0, x=...) at $HOME/persistent_vast/actor-framework/libcaf_core/src/scheduled_actor.cpp:599
#19 0x00007ffff719848e in caf::scheduled_actor::resume (this=0x7fffbc0017f0, ctx=<optimized out>, max_throughput=18446744073709551615) at $HOME/persistent_vast/actor-framework/libcaf_core/src/scheduled_actor.cpp:241
#20 0x00007ffff713edd3 in run (this=<optimized out>) at $HOME/persistent_vast/actor-framework/libcaf_core/caf/scheduler/worker.hpp:116
#21 operator() (__closure=<optimized out>) at $HOME/persistent_vast/actor-framework/libcaf_core/caf/scheduler/worker.hpp:58
#22 _M_invoke<> (this=<optimized out>) at /usr/local/include/c++/6.3.0/functional:1391
#23 operator() (this=<optimized out>) at /usr/local/include/c++/6.3.0/functional:1380
#24 std::thread::_State_impl<std::_Bind_simple<caf::scheduler::worker<caf::policy::work_stealing>::start()::{lambda()#1} ()> >::_M_run() (this=<optimized out>) at /usr/local/include/c++/6.3.0/thread:196
#25 0x00007ffff65b521f in std::execute_native_thread_routine (__p=0x66ff70) at ../../../../../gcc-6.3.0/libstdc++-v3/src/c++11/thread.cc:83
#26 0x00007ffff5a0ddc5 in start_thread (arg=0x7fffec7d9700) at pthread_create.c:308
#27 0x00007ffff5d1973d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

</details>

**Comment by mavam** [comment]
I may have fixed the bug. Would you mind testing your setup a few more times and see whether you can reproduce the crash?

**Comment by josephnoir** [comment]
Can't reproduce the crash anymore. This seems to have fixed it!
